/**
 * Demo data for testing enterprise features
 */

import type {
  Organization,
  OrgUser,
  SaaSTool,
  ToolSubscription,
  Decision,
  DashboardStats,
} from "./enterprise-api";

// Demo Organization
const demoOrganization: Organization = {
  id: "demo-org-id",
  name: "Acme Corporation",
  domain: "acme.com",
  plan: "enterprise",
  settings: {
    default_currency: "USD",
    fiscal_year_start: 1,
    approval_workflow: true,
  },
  sso_provider: "okta",
  created_at: "2024-01-15T00:00:00Z",
  updated_at: "2026-01-15T00:00:00Z",
};

// Demo Users
const demoUsers: OrgUser[] = [
  {
    id: "user-1",
    org_id: "demo-org-id",
    email: "john.smith@acme.com",
    name: "John Smith",
    department: "Engineering",
    job_title: "VP of Engineering",
    role: "admin",
    status: "active",
    last_login_at: "2026-01-17T10:30:00Z",
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "user-2",
    org_id: "demo-org-id",
    email: "sarah.jones@acme.com",
    name: "Sarah Jones",
    department: "Finance",
    job_title: "CFO",
    role: "finance",
    status: "active",
    last_login_at: "2026-01-16T14:20:00Z",
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "user-3",
    org_id: "demo-org-id",
    email: "mike.wilson@acme.com",
    name: "Mike Wilson",
    department: "IT",
    job_title: "IT Director",
    role: "it_admin",
    status: "active",
    last_login_at: "2026-01-17T09:00:00Z",
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "user-4",
    org_id: "demo-org-id",
    email: "emily.chen@acme.com",
    name: "Emily Chen",
    department: "Engineering",
    job_title: "Senior Developer",
    role: "member",
    status: "active",
    last_login_at: "2026-01-17T11:45:00Z",
    created_at: "2024-03-15T00:00:00Z",
  },
  {
    id: "user-5",
    org_id: "demo-org-id",
    email: "david.brown@acme.com",
    name: "David Brown",
    department: "Marketing",
    job_title: "Marketing Manager",
    role: "member",
    status: "active",
    last_login_at: "2026-01-15T16:30:00Z",
    created_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "user-6",
    org_id: "demo-org-id",
    email: "lisa.taylor@acme.com",
    name: "Lisa Taylor",
    department: "Sales",
    job_title: "Sales Director",
    role: "member",
    status: "active",
    last_login_at: "2026-01-16T08:15:00Z",
    created_at: "2024-05-01T00:00:00Z",
  },
  {
    id: "user-7",
    org_id: "demo-org-id",
    email: "former.employee@acme.com",
    name: "Former Employee",
    department: "Engineering",
    job_title: "Developer",
    role: "member",
    status: "offboarded",
    last_login_at: "2025-11-01T10:00:00Z",
    created_at: "2024-01-15T00:00:00Z",
  },
];

// Demo SaaS Tools
const demoTools: SaaSTool[] = [
  {
    id: "tool-1",
    org_id: "demo-org-id",
    name: "Slack",
    normalized_name: "slack",
    category: "communication",
    vendor_domain: "slack.com",
    vendor_url: "https://slack.com",
    logo_url: "https://logo.clearbit.com/slack.com",
    description: "Business messaging and collaboration platform",
    status: "active",
    is_keystone: true,
    keystone_score: 95,
    active_users: 142,
    total_users: 200,
    monthly_cost: 2400,
    dependency_count: 8,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "tool-2",
    org_id: "demo-org-id",
    name: "GitHub",
    normalized_name: "github",
    category: "dev_tools",
    vendor_domain: "github.com",
    vendor_url: "https://github.com",
    logo_url: "https://logo.clearbit.com/github.com",
    description: "Code hosting and version control platform",
    status: "active",
    is_keystone: true,
    keystone_score: 98,
    active_users: 85,
    total_users: 100,
    monthly_cost: 1900,
    dependency_count: 12,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "tool-3",
    org_id: "demo-org-id",
    name: "Figma",
    normalized_name: "figma",
    category: "productivity",
    vendor_domain: "figma.com",
    vendor_url: "https://figma.com",
    logo_url: "https://logo.clearbit.com/figma.com",
    description: "Collaborative design tool",
    status: "active",
    is_keystone: false,
    keystone_score: 45,
    active_users: 18,
    total_users: 45,
    monthly_cost: 1350,
    dependency_count: 2,
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "tool-4",
    org_id: "demo-org-id",
    name: "Zoom",
    normalized_name: "zoom",
    category: "communication",
    vendor_domain: "zoom.us",
    vendor_url: "https://zoom.us",
    logo_url: "https://logo.clearbit.com/zoom.us",
    description: "Video conferencing platform",
    status: "active",
    is_keystone: true,
    keystone_score: 88,
    active_users: 156,
    total_users: 200,
    monthly_cost: 3000,
    dependency_count: 5,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "tool-5",
    org_id: "demo-org-id",
    name: "Jira",
    normalized_name: "jira",
    category: "productivity",
    vendor_domain: "atlassian.com",
    vendor_url: "https://atlassian.com/jira",
    logo_url: "https://logo.clearbit.com/atlassian.com",
    description: "Project management and issue tracking",
    status: "active",
    is_keystone: true,
    keystone_score: 82,
    active_users: 78,
    total_users: 100,
    monthly_cost: 1500,
    dependency_count: 6,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "tool-6",
    org_id: "demo-org-id",
    name: "Notion",
    normalized_name: "notion",
    category: "productivity",
    vendor_domain: "notion.so",
    vendor_url: "https://notion.so",
    logo_url: "https://logo.clearbit.com/notion.so",
    description: "All-in-one workspace for notes and docs",
    status: "active",
    is_keystone: false,
    keystone_score: 55,
    active_users: 45,
    total_users: 80,
    monthly_cost: 800,
    dependency_count: 3,
    created_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "tool-7",
    org_id: "demo-org-id",
    name: "Salesforce",
    normalized_name: "salesforce",
    category: "sales",
    vendor_domain: "salesforce.com",
    vendor_url: "https://salesforce.com",
    logo_url: "https://logo.clearbit.com/salesforce.com",
    description: "Customer relationship management",
    status: "active",
    is_keystone: true,
    keystone_score: 90,
    active_users: 32,
    total_users: 40,
    monthly_cost: 6000,
    dependency_count: 7,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "tool-8",
    org_id: "demo-org-id",
    name: "HubSpot",
    normalized_name: "hubspot",
    category: "marketing",
    vendor_domain: "hubspot.com",
    vendor_url: "https://hubspot.com",
    logo_url: "https://logo.clearbit.com/hubspot.com",
    description: "Marketing automation platform",
    status: "active",
    is_keystone: false,
    keystone_score: 60,
    active_users: 12,
    total_users: 25,
    monthly_cost: 1600,
    dependency_count: 4,
    created_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "tool-9",
    org_id: "demo-org-id",
    name: "1Password",
    normalized_name: "1password",
    category: "security",
    vendor_domain: "1password.com",
    vendor_url: "https://1password.com",
    logo_url: "https://logo.clearbit.com/1password.com",
    description: "Password management for teams",
    status: "active",
    is_keystone: true,
    keystone_score: 85,
    active_users: 180,
    total_users: 200,
    monthly_cost: 800,
    dependency_count: 0,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "tool-10",
    org_id: "demo-org-id",
    name: "Asana",
    normalized_name: "asana",
    category: "productivity",
    vendor_domain: "asana.com",
    vendor_url: "https://asana.com",
    logo_url: "https://logo.clearbit.com/asana.com",
    description: "Work management platform",
    status: "active",
    is_keystone: false,
    keystone_score: 35,
    active_users: 8,
    total_users: 30,
    monthly_cost: 450,
    dependency_count: 1,
    created_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "tool-11",
    org_id: "demo-org-id",
    name: "Dropbox",
    normalized_name: "dropbox",
    category: "productivity",
    vendor_domain: "dropbox.com",
    vendor_url: "https://dropbox.com",
    logo_url: "https://logo.clearbit.com/dropbox.com",
    description: "Cloud file storage and sharing",
    status: "under_review",
    is_keystone: false,
    keystone_score: 25,
    active_users: 5,
    total_users: 50,
    monthly_cost: 750,
    dependency_count: 0,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "tool-12",
    org_id: "demo-org-id",
    name: "Monday.com",
    normalized_name: "monday",
    category: "productivity",
    vendor_domain: "monday.com",
    vendor_url: "https://monday.com",
    logo_url: "https://logo.clearbit.com/monday.com",
    description: "Work operating system",
    status: "active",
    is_keystone: false,
    keystone_score: 30,
    active_users: 6,
    total_users: 25,
    monthly_cost: 500,
    dependency_count: 0,
    created_at: "2024-06-01T00:00:00Z",
  },
];

// Demo Subscriptions
const demoSubscriptions: ToolSubscription[] = [
  {
    id: "sub-1",
    org_id: "demo-org-id",
    tool_id: "tool-1",
    plan_name: "Business+",
    billing_cycle: "monthly",
    amount_cents: 240000,
    currency: "USD",
    paid_seats: 200,
    active_seats: 142,
    renewal_date: "2026-02-01",
    auto_renew: true,
    owner_id: "user-3",
    department: "IT",
    status: "active",
    tool_name: "Slack",
    owner_name: "Mike Wilson",
    owner_status: "active",
    utilization_rate: 71,
    days_until_renewal: 14,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "sub-2",
    org_id: "demo-org-id",
    tool_id: "tool-2",
    plan_name: "Enterprise",
    billing_cycle: "annual",
    amount_cents: 2280000,
    currency: "USD",
    paid_seats: 100,
    active_seats: 85,
    renewal_date: "2026-06-15",
    auto_renew: true,
    owner_id: "user-1",
    department: "Engineering",
    status: "active",
    tool_name: "GitHub",
    owner_name: "John Smith",
    owner_status: "active",
    utilization_rate: 85,
    days_until_renewal: 148,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "sub-3",
    org_id: "demo-org-id",
    tool_id: "tool-3",
    plan_name: "Organization",
    billing_cycle: "monthly",
    amount_cents: 135000,
    currency: "USD",
    paid_seats: 45,
    active_seats: 18,
    renewal_date: "2026-02-01",
    auto_renew: true,
    owner_id: "user-4",
    department: "Engineering",
    status: "active",
    tool_name: "Figma",
    owner_name: "Emily Chen",
    owner_status: "active",
    utilization_rate: 40,
    days_until_renewal: 14,
    created_at: "2024-02-01T00:00:00Z",
  },
  {
    id: "sub-4",
    org_id: "demo-org-id",
    tool_id: "tool-4",
    plan_name: "Business",
    billing_cycle: "monthly",
    amount_cents: 300000,
    currency: "USD",
    paid_seats: 200,
    active_seats: 156,
    renewal_date: "2026-02-15",
    auto_renew: true,
    owner_id: "user-3",
    department: "IT",
    status: "active",
    tool_name: "Zoom",
    owner_name: "Mike Wilson",
    owner_status: "active",
    utilization_rate: 78,
    days_until_renewal: 28,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "sub-5",
    org_id: "demo-org-id",
    tool_id: "tool-5",
    plan_name: "Premium",
    billing_cycle: "annual",
    amount_cents: 1800000,
    currency: "USD",
    paid_seats: 100,
    active_seats: 78,
    renewal_date: "2026-04-01",
    auto_renew: true,
    owner_id: "user-1",
    department: "Engineering",
    status: "active",
    tool_name: "Jira",
    owner_name: "John Smith",
    owner_status: "active",
    utilization_rate: 78,
    days_until_renewal: 73,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "sub-6",
    org_id: "demo-org-id",
    tool_id: "tool-6",
    plan_name: "Team",
    billing_cycle: "monthly",
    amount_cents: 80000,
    currency: "USD",
    paid_seats: 80,
    active_seats: 45,
    renewal_date: "2026-02-01",
    auto_renew: true,
    owner_id: "user-4",
    department: "Engineering",
    status: "active",
    tool_name: "Notion",
    owner_name: "Emily Chen",
    owner_status: "active",
    utilization_rate: 56,
    days_until_renewal: 14,
    created_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "sub-7",
    org_id: "demo-org-id",
    tool_id: "tool-7",
    plan_name: "Enterprise",
    billing_cycle: "annual",
    amount_cents: 7200000,
    currency: "USD",
    paid_seats: 40,
    active_seats: 32,
    renewal_date: "2026-03-15",
    auto_renew: true,
    owner_id: "user-6",
    department: "Sales",
    status: "active",
    tool_name: "Salesforce",
    owner_name: "Lisa Taylor",
    owner_status: "active",
    utilization_rate: 80,
    days_until_renewal: 56,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "sub-8",
    org_id: "demo-org-id",
    tool_id: "tool-8",
    plan_name: "Professional",
    billing_cycle: "monthly",
    amount_cents: 160000,
    currency: "USD",
    paid_seats: 25,
    active_seats: 12,
    renewal_date: "2026-02-01",
    auto_renew: true,
    owner_id: "user-5",
    department: "Marketing",
    status: "active",
    tool_name: "HubSpot",
    owner_name: "David Brown",
    owner_status: "active",
    utilization_rate: 48,
    days_until_renewal: 14,
    created_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "sub-9",
    org_id: "demo-org-id",
    tool_id: "tool-9",
    plan_name: "Teams",
    billing_cycle: "annual",
    amount_cents: 960000,
    currency: "USD",
    paid_seats: 200,
    active_seats: 180,
    renewal_date: "2026-07-01",
    auto_renew: true,
    owner_id: "user-3",
    department: "IT",
    status: "active",
    tool_name: "1Password",
    owner_name: "Mike Wilson",
    owner_status: "active",
    utilization_rate: 90,
    days_until_renewal: 164,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "sub-10",
    org_id: "demo-org-id",
    tool_id: "tool-10",
    plan_name: "Premium",
    billing_cycle: "monthly",
    amount_cents: 45000,
    currency: "USD",
    paid_seats: 30,
    active_seats: 8,
    renewal_date: "2026-02-01",
    auto_renew: true,
    owner_id: "user-5",
    department: "Marketing",
    status: "active",
    tool_name: "Asana",
    owner_name: "David Brown",
    owner_status: "active",
    utilization_rate: 27,
    days_until_renewal: 14,
    created_at: "2024-04-01T00:00:00Z",
  },
  {
    id: "sub-11",
    org_id: "demo-org-id",
    tool_id: "tool-11",
    plan_name: "Business",
    billing_cycle: "annual",
    amount_cents: 900000,
    currency: "USD",
    paid_seats: 50,
    active_seats: 5,
    renewal_date: "2026-01-25",
    auto_renew: true,
    owner_id: "user-7",
    department: "Engineering",
    status: "active",
    tool_name: "Dropbox",
    owner_name: "Former Employee",
    owner_status: "offboarded",
    utilization_rate: 10,
    days_until_renewal: 7,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "sub-12",
    org_id: "demo-org-id",
    tool_id: "tool-12",
    plan_name: "Pro",
    billing_cycle: "monthly",
    amount_cents: 50000,
    currency: "USD",
    paid_seats: 25,
    active_seats: 6,
    renewal_date: "2026-02-01",
    auto_renew: true,
    owner_id: "user-5",
    department: "Marketing",
    status: "active",
    tool_name: "Monday.com",
    owner_name: "David Brown",
    owner_status: "active",
    utilization_rate: 24,
    days_until_renewal: 14,
    created_at: "2024-06-01T00:00:00Z",
  },
];

// Demo Decisions
const demoDecisions: Decision[] = [
  {
    id: "dec-1",
    org_id: "demo-org-id",
    subscription_id: "sub-1",
    tool_id: "tool-1",
    decision_type: "downsize",
    confidence: 0.85,
    risk_score: 0.2,
    savings_potential_cents: 69600,
    recommended_seats: 150,
    current_seats: 200,
    explanation: "58 Slack seats are unused. Reducing to 150 seats would save $696/month while maintaining 5% buffer for growth.",
    factors: [
      { type: "utilization", value: 71, threshold: 80 },
      { type: "trend", direction: "stable" },
      { type: "last_active", days_inactive: 45 },
    ],
    status: "pending",
    priority: "high",
    due_date: "2026-01-25",
    tool_name: "Slack",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "dec-2",
    org_id: "demo-org-id",
    subscription_id: "sub-3",
    tool_id: "tool-3",
    decision_type: "downsize",
    confidence: 0.92,
    risk_score: 0.15,
    savings_potential_cents: 81000,
    recommended_seats: 25,
    current_seats: 45,
    explanation: "Only 18 out of 45 Figma seats are actively used. Recommend reducing to 25 seats to save $810/month.",
    factors: [
      { type: "utilization", value: 40, threshold: 60 },
      { type: "department_usage", low_usage_depts: ["Marketing", "Sales"] },
    ],
    status: "pending",
    priority: "high",
    due_date: "2026-01-28",
    tool_name: "Figma",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "dec-3",
    org_id: "demo-org-id",
    subscription_id: "sub-11",
    tool_id: "tool-11",
    decision_type: "cancel",
    confidence: 0.95,
    risk_score: 0.1,
    savings_potential_cents: 75000,
    explanation: "Dropbox has only 10% utilization and the owner has been offboarded. Most users have migrated to Google Drive. Recommend cancellation.",
    factors: [
      { type: "utilization", value: 10, threshold: 30 },
      { type: "owner_status", status: "offboarded" },
      { type: "alternative_tool", name: "Google Drive" },
    ],
    status: "pending",
    priority: "urgent",
    due_date: "2026-01-20",
    tool_name: "Dropbox",
    created_at: "2026-01-10T00:00:00Z",
  },
  {
    id: "dec-4",
    org_id: "demo-org-id",
    subscription_id: "sub-10",
    tool_id: "tool-10",
    decision_type: "cancel",
    confidence: 0.88,
    risk_score: 0.25,
    savings_potential_cents: 45000,
    explanation: "Asana overlaps significantly with Jira. Only 8 users are active and they also use Jira. Recommend consolidating to Jira.",
    factors: [
      { type: "utilization", value: 27, threshold: 50 },
      { type: "overlap", with_tool: "Jira", overlap_users: 6 },
    ],
    status: "pending",
    priority: "normal",
    due_date: "2026-02-01",
    tool_name: "Asana",
    created_at: "2026-01-12T00:00:00Z",
  },
  {
    id: "dec-5",
    org_id: "demo-org-id",
    subscription_id: "sub-12",
    tool_id: "tool-12",
    decision_type: "review",
    confidence: 0.75,
    risk_score: 0.3,
    savings_potential_cents: 35000,
    explanation: "Monday.com has low utilization (24%) and overlaps with existing project management tools. Recommend reviewing necessity with Marketing team.",
    factors: [
      { type: "utilization", value: 24, threshold: 50 },
      { type: "overlap", with_tool: "Jira", overlap_users: 2 },
    ],
    status: "pending",
    priority: "normal",
    due_date: "2026-02-05",
    tool_name: "Monday.com",
    created_at: "2026-01-14T00:00:00Z",
  },
  {
    id: "dec-6",
    org_id: "demo-org-id",
    subscription_id: "sub-8",
    tool_id: "tool-8",
    decision_type: "downsize",
    confidence: 0.82,
    risk_score: 0.2,
    savings_potential_cents: 83200,
    recommended_seats: 15,
    current_seats: 25,
    explanation: "HubSpot has 48% utilization. 13 seats are unused. Recommend reducing to 15 seats to save $832/month.",
    factors: [
      { type: "utilization", value: 48, threshold: 70 },
      { type: "inactive_users", count: 13 },
    ],
    status: "pending",
    priority: "normal",
    due_date: "2026-02-01",
    tool_name: "HubSpot",
    created_at: "2026-01-13T00:00:00Z",
  },
  {
    id: "dec-7",
    org_id: "demo-org-id",
    subscription_id: "sub-4",
    tool_id: "tool-4",
    decision_type: "downsize",
    confidence: 0.78,
    risk_score: 0.35,
    savings_potential_cents: 66000,
    recommended_seats: 175,
    current_seats: 200,
    explanation: "Zoom has 78% utilization. 44 seats are unused. Consider reducing to 175 seats to save $660/month while keeping buffer for meetings.",
    factors: [
      { type: "utilization", value: 78, threshold: 85 },
      { type: "usage_pattern", peak_concurrent: 145 },
    ],
    status: "pending",
    priority: "low",
    due_date: "2026-02-15",
    tool_name: "Zoom",
    created_at: "2026-01-14T00:00:00Z",
  },
  {
    id: "dec-8",
    org_id: "demo-org-id",
    subscription_id: "sub-2",
    tool_id: "tool-2",
    decision_type: "keep",
    confidence: 0.95,
    risk_score: 0.05,
    savings_potential_cents: 0,
    explanation: "GitHub is a keystone tool with 85% utilization and high dependency score. No action recommended.",
    factors: [
      { type: "keystone", score: 98 },
      { type: "utilization", value: 85, threshold: 80 },
      { type: "dependency_count", count: 12 },
    ],
    status: "approved",
    priority: "low",
    tool_name: "GitHub",
    created_at: "2026-01-10T00:00:00Z",
  },
  {
    id: "dec-9",
    org_id: "demo-org-id",
    subscription_id: "sub-6",
    tool_id: "tool-6",
    decision_type: "downsize",
    confidence: 0.8,
    risk_score: 0.25,
    savings_potential_cents: 35000,
    recommended_seats: 55,
    current_seats: 80,
    explanation: "Notion has 56% utilization. 35 seats unused. Recommend reducing to 55 seats to save $350/month.",
    factors: [
      { type: "utilization", value: 56, threshold: 70 },
      { type: "inactive_users", count: 35 },
    ],
    status: "pending",
    priority: "normal",
    due_date: "2026-02-01",
    tool_name: "Notion",
    created_at: "2026-01-15T00:00:00Z",
  },
];

// Dashboard Stats
const demoStats: DashboardStats = {
  total_tools: 12,
  active_subscriptions: 12,
  total_users: 200,
  monthly_spend_cents: 2026000,
  annual_spend_cents: 24312000,
  potential_savings_cents: 489800,
  pending_decisions: 8,
  tools_under_review: 2,
  avg_utilization: 54,
};

// Quick Wins
const demoQuickWins = [
  {
    type: "license_reduction",
    subscription_id: "sub-1",
    tool_name: "Slack",
    potential_annual_savings_cents: 835200,
    action: "Reduce from 200 to 150 seats",
    priority: "high",
  },
  {
    type: "license_reduction",
    subscription_id: "sub-3",
    tool_name: "Figma",
    potential_annual_savings_cents: 972000,
    action: "Reduce from 45 to 25 seats",
    priority: "high",
  },
  {
    type: "cancellation",
    subscription_id: "sub-11",
    tool_name: "Dropbox",
    potential_annual_savings_cents: 900000,
    action: "Cancel - only 10% utilization, owner offboarded",
    priority: "urgent",
  },
  {
    type: "consolidation",
    category: "project_management",
    tool_count: 3,
    potential_annual_savings_cents: 960000,
    action: "Consolidate Jira, Asana, Monday.com",
    priority: "normal",
  },
];

// Utilization Summary
const demoUtilizationSummary = {
  healthy_count: 4,
  moderate_count: 3,
  underutilized_count: 4,
  critical_count: 1,
  total_monthly_waste_cents: 325000,
};

// Export the hook
export function useDemoData() {
  return {
    organization: demoOrganization,
    users: demoUsers,
    tools: demoTools,
    subscriptions: demoSubscriptions,
    decisions: demoDecisions,
    stats: demoStats,
    quickWins: demoQuickWins,
    utilizationSummary: demoUtilizationSummary,
  };
}

// Export individual data for direct use
export {
  demoOrganization,
  demoUsers,
  demoTools,
  demoSubscriptions,
  demoDecisions,
  demoStats,
  demoQuickWins,
  demoUtilizationSummary,
};
